{
  "openapi": "3.0.3",
  "info": {
    "title": "SIF SaaS: Pipeline Executions Management",
    "description": "\nHas accountability for:\n- Vending pre-signed URLs for:\n\t- uploading pipeline input files\n\t- downloading pipeline output files\n\t- downloading pipeline error files\n- Requesting pipeline execution status \n",
    "version": "0.0.1"
  },
  "components": {
    "securitySchemes": {
      "platformUserPool": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      }
    },
    "schemas": {
      "pipelineExecution_request": {
        "type": "object",
        "properties": {
          "inlineExecutionOptions": {
            "type": "object",
            "properties": {
              "inputs": {
                "maxItems": 10,
                "type": "array",
                "items": {
                  "description": "An object with key values representing the inputs and its expected values.",
                  "type": "object",
                  "additionalProperties": {
                    "type": "string"
                  }
                }
              }
            },
            "required": [
              "inputs"
            ]
          },
          "mode": {
            "description": "Pipeline execution mode, inline will run the calculation synchronously.",
            "default": "job",
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "inline"
                ]
              },
              {
                "type": "string",
                "enum": [
                  "job"
                ]
              }
            ]
          },
          "actionType": {
            "description": "Type of operation to perform in this pipeline execution.",
            "default": "create",
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "create"
                ]
              },
              {
                "type": "string",
                "enum": [
                  "delete"
                ]
              }
            ]
          },
          "expiration": {
            "description": "The number of seconds before file upload url expires in, default to 5 minutes",
            "default": 300,
            "type": "number"
          },
          "connectorOverrides": {
            "description": "any overrides for the connectors which are configured on for the pipeline",
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "parameters": {
                  "description": "any key:val attributes to pass config parameters through the input connector.",
                  "type": "object",
                  "additionalProperties": {}
                }
              },
              "required": [
                "parameters"
              ]
            }
          }
        },
        "required": [
          "mode",
          "actionType",
          "expiration"
        ]
      },
      "pipelineExecution_full": {
        "type": "object",
        "properties": {
          "actionType": {
            "description": "Type of operation to perform in this pipeline execution.",
            "default": "create",
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "create"
                ]
              },
              {
                "type": "string",
                "enum": [
                  "delete"
                ]
              }
            ]
          },
          "createdAt": {
            "description": "Date/time created.",
            "format": "date-time",
            "type": "string"
          },
          "createdBy": {
            "description": "Email of the user who created the pipeline.",
            "type": "string"
          },
          "executionArn": {
            "description": "Step Function execution arn.",
            "type": "string"
          },
          "id": {
            "description": "Unique id.",
            "type": "string"
          },
          "inputUploadUrl": {
            "description": "this property depends on if the execution requires a file uploaded for the execution. By default it generates a signed url for files which are in SIF format.",
            "type": "string"
          },
          "pipelineId": {
            "description": "Identifier of the pipeline configuration.",
            "type": "string"
          },
          "pipelineVersion": {
            "description": "The version of the pipeline when the execution is created.",
            "type": "number"
          },
          "connectorOverrides": {
            "description": "any overrides for the connectors which are configured on for the pipeline",
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "parameters": {
                  "description": "any key:val attributes to pass config parameters through the input connector.",
                  "type": "object",
                  "additionalProperties": {}
                }
              },
              "required": [
                "parameters"
              ]
            }
          },
          "status": {
            "description": "Status of the pipeline execution.",
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "waiting"
                ]
              },
              {
                "type": "string",
                "enum": [
                  "in_progress"
                ]
              },
              {
                "type": "string",
                "enum": [
                  "success"
                ]
              },
              {
                "type": "string",
                "enum": [
                  "failed"
                ]
              }
            ]
          },
          "statusMessage": {
            "description": "Execution status details message, in case there is meaningful message which needs to be reported, this property will be present with the message details.",
            "type": "string"
          },
          "groupContextId": {
            "description": "security context id of the creator of this execution",
            "type": "string"
          },
          "updatedAt": {
            "description": "Date/time updated.",
            "format": "date-time",
            "type": "string"
          },
          "updatedBy": {
            "description": "Email of the user who updated the pipeline.",
            "type": "string"
          },
          "inlineExecutionOutputs": {
            "type": "object",
            "properties": {
              "errors": {
                "description": "List of error when processing the input rows.",
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "outputs": {
                "type": "array",
                "items": {
                  "description": "An object with key values representing the outputs and its expected values.",
                  "type": "object",
                  "additionalProperties": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "required": [
          "actionType",
          "createdAt",
          "createdBy",
          "id",
          "pipelineId",
          "pipelineVersion",
          "status",
          "groupContextId"
        ]
      },
      "pipelineExecution_list": {
        "type": "object",
        "properties": {
          "executions": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/pipelineExecution_full"
            }
          },
          "pagination": {
            "type": "object",
            "properties": {
              "lastEvaluated": {
                "type": "object",
                "properties": {
                  "executionId": {
                    "description": "Pipeline execution ID to paginate from (exclusive).",
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "required": [
          "executions"
        ]
      },
      "signedUrl_request": {
        "type": "object",
        "properties": {
          "expiration": {
            "description": "The number of seconds before presigned url expires, default to 5 minutes",
            "type": "number"
          }
        }
      },
      "signedUrlUploadInput_request": {
        "type": "object",
        "properties": {
          "actionType": {
            "description": "Type of operation to perform in this pipeline execution.",
            "default": "create",
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "create"
                ]
              },
              {
                "type": "string",
                "enum": [
                  "delete"
                ]
              }
            ]
          },
          "expiration": {
            "description": "The number of seconds before presigned url expires, default to 5 minutes",
            "type": "number"
          }
        },
        "required": [
          "actionType"
        ]
      },
      "signedUrl_response": {
        "type": "object",
        "properties": {
          "url": {
            "description": "requested signed url",
            "type": "string"
          }
        },
        "required": [
          "url"
        ]
      },
      "signedUrlList_response": {
        "type": "object",
        "properties": {
          "urls": {
            "description": "list of audit files signed url",
            "type": "array",
            "items": {
              "description": "requested signed url",
              "type": "string"
            }
          }
        },
        "required": [
          "urls"
        ]
      },
      "activityResource": {
        "description": "Processed activities.",
        "type": "object",
        "additionalProperties": {
          "description": "Value`.",
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "number"
            },
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "activitiesList": {
        "type": "object",
        "properties": {
          "activities": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/activityResource"
            }
          },
          "pagination": {
            "type": "object",
            "properties": {
              "lastEvaluatedToken": {
                "description": "Token used to paginate to the next page of search result.",
                "type": "number"
              }
            }
          }
        },
        "required": [
          "activities"
        ]
      },
      "metricResource": {
        "type": "object",
        "properties": {
          "date": {},
          "metricId": {
            "description": "Id of metric.",
            "type": "string"
          },
          "name": {
            "description": "Name of metric.",
            "type": "string"
          },
          "timeUnit": {
            "type": "string",
            "enum": [
              "day",
              "week",
              "month",
              "quarter",
              "year"
            ],
            "description": "Time unit the metric represents."
          },
          "day": {
            "description": "Day of year of the metric. Applies to `day` time unit only.",
            "type": "integer"
          },
          "week": {
            "description": "Week of year of the metric. Applies to `week` time unit only.",
            "type": "integer"
          },
          "month": {
            "description": "Month of year of the metric. Applies to `month` time unit only.",
            "type": "integer"
          },
          "quarter": {
            "description": "Quarter of year of the metric. Applies to `quarter` time unit only.",
            "type": "integer"
          },
          "year": {
            "description": "Year of the metric.",
            "type": "integer"
          },
          "hierarchyValue": {
            "description": "Value of the metric for the current group hierarchy, combination of group and sub groups",
            "type": "number"
          },
          "groupValue": {
            "description": "Value of the metric for the current group.",
            "type": "number"
          },
          "subGroupsValue": {
            "description": "Value of the metric for the sub groups",
            "type": "number"
          },
          "version": {
            "description": "Version of the metric.",
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "string"
              }
            ]
          },
          "groupId": {
            "description": "group of the metric",
            "type": "string"
          }
        },
        "required": [
          "date",
          "metricId",
          "name",
          "timeUnit",
          "year",
          "groupValue",
          "subGroupsValue",
          "version"
        ]
      },
      "metricsList": {
        "type": "object",
        "properties": {
          "metrics": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/metricResource"
            }
          }
        },
        "required": [
          "metrics"
        ]
      }
    }
  },
  "paths": {
    "/pipelines/{pipelineId}/executions/{executionId}/errorDownloadUrl": {
      "post": {
        "tags": [
          "Pipelines"
        ],
        "description": "Returns a pre-signed URL to download the pipeline errors file.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/signedUrl_request"
              },
              "examples": {
                "New download error signedUrl request": {
                  "expiration": 2000
                }
              }
            }
          }
        },
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "path",
            "name": "pipelineId",
            "required": true,
            "description": "Unique id."
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "path",
            "name": "executionId",
            "required": true,
            "description": "Identifier of a execution of the pipeline."
          },
          {
            "in": "header",
            "name": "accept-version",
            "required": true,
            "description": "API version",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "header",
            "name": "accept",
            "required": true,
            "description": "Accepted Content Type",
            "schema": {
              "type": "string"
            }
          }
        ],
        "x-security-scopes": [
          "contributor",
          "admin",
          "superAdmin"
        ],
        "responses": {
          "201": {
            "description": "Success.",
            "content": {
              "application/json": {
                "schema": {
                  "description": "Success.",
                  "$ref": "#/components/schemas/signedUrl_response"
                },
                "examples": {
                  "Pipeline Execution Error Download Url": {
                    "summary": "pipeline execution error download url",
                    "value": {
                      "url": "s3-signed-url..."
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request.",
            "content": {
              "application/json": {
                "schema": {
                  "description": "Bad request.",
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "message"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/pipelines/{pipelineId}/executions/{executionId}": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "description": "Retrieve details of a specific execution of the pipeline.",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "path",
            "name": "pipelineId",
            "required": true,
            "description": "Unique id."
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "path",
            "name": "executionId",
            "required": true,
            "description": "Identifier of a execution of the pipeline."
          },
          {
            "in": "header",
            "name": "accept-version",
            "required": true,
            "description": "API version",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "header",
            "name": "accept",
            "required": true,
            "description": "Accepted Content Type",
            "schema": {
              "type": "string"
            }
          }
        ],
        "x-security-scopes": [
          "reader",
          "contributor",
          "admin",
          "superAdmin"
        ],
        "responses": {
          "200": {
            "description": "Success.",
            "content": {
              "application/json": {
                "schema": {
                  "description": "Success.",
                  "$ref": "#/components/schemas/pipelineExecution_full"
                },
                "examples": {
                  "Existing pipeline successful execution details": {
                    "summary": "Existing pipeline successful execution details.",
                    "value": {
                      "id": "ajcuhek13ks",
                      "pipelineId": "7777777",
                      "createdAt": "2022-08-10T23:55:20.322Z",
                      "updatedAt": "2022-08-10T23:55:20.322Z",
                      "createdBy": "",
                      "updatedBy": "someone@somewhere.com",
                      "status": "in_progress",
                      "pipelineVersion": 1,
                      "actionType": "create",
                      "groupContextId": "/"
                    }
                  },
                  "Existing pipeline failed execution details": {
                    "summary": "Existing pipeline failed execution details.",
                    "value": {
                      "id": "ajcuhek13ks",
                      "pipelineId": "7777777",
                      "createdAt": "2022-08-10T23:55:20.322Z",
                      "updatedAt": "2022-08-10T23:55:20.322Z",
                      "status": "failed",
                      "createdBy": "someone@somewhere.com",
                      "updatedBy": "someone@somewhere.com",
                      "pipelineVersion": 1,
                      "statusMessage": "some validation error related to input file",
                      "actionType": "create",
                      "groupContextId": "/"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found.",
            "content": {
              "application/json": {
                "schema": {
                  "description": "Not found.",
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "message"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/pipelines/{pipelineId}/executions": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "description": "Lists executions of a pipeline.",
        "parameters": [
          {
            "schema": {
              "type": "integer"
            },
            "in": "query",
            "name": "count",
            "required": false,
            "description": "Count of results to return."
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "fromExecutionId",
            "required": false,
            "description": "Pipeline execution ID to paginate from (exclusive)."
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "path",
            "name": "pipelineId",
            "required": true,
            "description": "Unique id."
          },
          {
            "in": "header",
            "name": "accept-version",
            "required": true,
            "description": "API version",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "header",
            "name": "accept",
            "required": true,
            "description": "Accepted Content Type",
            "schema": {
              "type": "string"
            }
          }
        ],
        "x-security-scopes": [
          "reader",
          "contributor",
          "admin",
          "superAdmin"
        ],
        "responses": {
          "200": {
            "description": "Success.",
            "content": {
              "application/json": {
                "schema": {
                  "description": "Success.",
                  "$ref": "#/components/schemas/pipelineExecution_list"
                },
                "examples": {
                  "List of pipeline executions": {
                    "summary": "Paginated list of pipelines executions",
                    "value": {
                      "executions": [
                        {
                          "id": "ajcuhek13ks",
                          "pipelineId": "7777777",
                          "createdAt": "2022-08-10T23:55:20.322Z",
                          "updatedAt": "2022-08-10T23:55:20.322Z",
                          "createdBy": "",
                          "updatedBy": "someone@somewhere.com",
                          "status": "in_progress",
                          "pipelineVersion": 1,
                          "actionType": "create",
                          "groupContextId": "/"
                        },
                        {
                          "id": "ajcuhek13ks",
                          "pipelineId": "7777777",
                          "createdAt": "2022-08-10T23:55:20.322Z",
                          "updatedAt": "2022-08-10T23:55:20.322Z",
                          "status": "failed",
                          "createdBy": "someone@somewhere.com",
                          "updatedBy": "someone@somewhere.com",
                          "pipelineVersion": 1,
                          "statusMessage": "some validation error related to input file",
                          "actionType": "create",
                          "groupContextId": "/"
                        }
                      ],
                      "pagination": {
                        "lastEvaluated": {
                          "executionId": "ajcuhek13ks"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Pipeline Executions"
        ],
        "description": "Creates a new execution for a pipeline",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/pipelineExecution_request"
              },
              "examples": {
                "Pipeline Execution request example": {
                  "expiration": 2000,
                  "mode": "job",
                  "actionType": "create",
                  "connectorOverrides": {
                    "sif-csv-input-converter": {
                      "parameters": {
                        "key1": "val1",
                        "key2": "val2"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "path",
            "name": "pipelineId",
            "required": true,
            "description": "Unique id."
          },
          {
            "in": "header",
            "name": "accept-version",
            "required": true,
            "description": "API version",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "header",
            "name": "accept",
            "required": true,
            "description": "Accepted Content Type",
            "schema": {
              "type": "string"
            }
          }
        ],
        "x-security-scopes": [
          "contributor",
          "admin",
          "superAdmin"
        ],
        "responses": {
          "201": {
            "description": "Success.",
            "content": {
              "application/json": {
                "schema": {
                  "description": "Success.",
                  "$ref": "#/components/schemas/pipelineExecution_full"
                },
                "examples": {
                  "Pipeline Execution creation response": {
                    "summary": "pipeline execution response",
                    "value": {
                      "id": "ajcuhek13ks",
                      "pipelineId": "7777777",
                      "createdAt": "2022-08-10T23:55:20.322Z",
                      "updatedAt": "2022-08-10T23:55:20.322Z",
                      "createdBy": "",
                      "updatedBy": "someone@somewhere.com",
                      "status": "in_progress",
                      "pipelineVersion": 1,
                      "actionType": "create",
                      "groupContextId": "/"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request.",
            "content": {
              "application/json": {
                "schema": {
                  "description": "Bad request.",
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "message"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/activities/{id}/audits": {
      "get": {
        "operationId": "list",
        "tags": [
          "Audits"
        ],
        "description": "Retrieve list of audit information for an activity.",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "versionAsAt",
            "required": false,
            "description": "Filters by `asAt` or `createdAt` determine the latest resource version as that time."
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "path",
            "name": "id",
            "required": true,
            "description": "Unique id."
          },
          {
            "in": "header",
            "name": "accept-version",
            "required": true,
            "description": "API version",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "header",
            "name": "accept",
            "required": true,
            "description": "Accepted Content Type",
            "schema": {
              "type": "string"
            }
          }
        ],
        "x-security-scopes": [
          "reader",
          "contributor",
          "admin",
          "superAdmin"
        ],
        "responses": {
          "200": {
            "description": "Success.",
            "content": {
              "application/json": {
                "schema": {
                  "description": "Success.",
                  "type": "array",
                  "items": {
                    "description": "The audit information for an activity.",
                    "type": "object",
                    "additionalProperties": {}
                  }
                },
                "examples": {
                  "List of audit versions for an activity": {
                    "summary": "Audit detail.",
                    "value": [
                      {
                        "activityId": 1144,
                        "date": "2022-01-03T16:00:00.000Z",
                        "pipelineId": "01gwh2f5zwqryq789v42g1akrz",
                        "executionId": "01gwh2hpz1dbpskw8vq531jg94",
                        "auditId": "8e50a420-c138-406b-a794-4f1e973018f5",
                        "createdAt": "2023-03-27T00:21:58.322Z",
                        "executionNo": 0,
                        "outputs": [
                          {
                            "index": 0,
                            "name": "time",
                            "formula": "AS_TIMESTAMP(:reading date,'M/d/yy')",
                            "evaluated": {
                              "AS_TIMESTAMP(:reading date,'M/d/yy')": "1641254400000",
                              ":reading date": "1/4/22"
                            },
                            "result": "1641254400000"
                          },
                          {
                            "index": 1,
                            "name": "month",
                            "formula": "AS_TIMESTAMP(:reading date,'M/d/yy', roundDownTo='month')",
                            "evaluated": {
                              "AS_TIMESTAMP(:reading date,'M/d/yy', roundDownTo='month')": "1640995200000",
                              ":reading date": "1/4/22"
                            },
                            "result": "1640995200000"
                          },
                          {
                            "index": 2,
                            "name": "a",
                            "formula": ":a",
                            "evaluated": {
                              ":a": "A"
                            },
                            "result": "A"
                          },
                          {
                            "index": 3,
                            "name": "b*c",
                            "formula": ":b*:c",
                            "evaluated": {
                              ":b": "10",
                              ":c": "1"
                            },
                            "result": "10"
                          }
                        ]
                      },
                      {
                        "activityId": 1144,
                        "date": "2022-01-03T16:00:00.000Z",
                        "pipelineId": "01gwh2f5zwqryq789v42g1akrz",
                        "executionId": "01gwh2g8k79v4qfq4m9pvz05q1",
                        "auditId": "5ca76cb8-bb74-4a7b-ac9c-31b1b594b1f7",
                        "createdAt": "2023-03-27T00:21:11.104Z",
                        "executionNo": 0,
                        "outputs": [
                          {
                            "index": 0,
                            "name": "time",
                            "formula": "AS_TIMESTAMP(:reading date,'M/d/yy')",
                            "evaluated": {
                              "AS_TIMESTAMP(:reading date,'M/d/yy')": "1641254400000",
                              ":reading date": "1/4/22"
                            },
                            "result": "1641254400000"
                          },
                          {
                            "index": 1,
                            "name": "month",
                            "formula": "AS_TIMESTAMP(:reading date,'M/d/yy', roundDownTo='month')",
                            "evaluated": {
                              "AS_TIMESTAMP(:reading date,'M/d/yy', roundDownTo='month')": "1640995200000",
                              ":reading date": "1/4/22"
                            },
                            "result": "1640995200000"
                          },
                          {
                            "index": 2,
                            "name": "a",
                            "formula": ":a",
                            "evaluated": {
                              ":a": "A"
                            },
                            "result": "A"
                          },
                          {
                            "index": 3,
                            "name": "b*c",
                            "formula": ":b*:c"
                          }
                        ]
                      },
                      {
                        "activityId": 1144,
                        "date": "2022-01-03T16:00:00.000Z",
                        "pipelineId": "01gwh2f5zwqryq789v42g1akrz",
                        "executionId": "01gwh2fb3g2e33ghb08pab5hma",
                        "auditId": "80eda70e-cc36-480e-9b95-6c010cf951d0",
                        "createdAt": "2023-03-27T00:20:52.759Z",
                        "executionNo": 0,
                        "outputs": [
                          {
                            "index": 0,
                            "name": "time",
                            "formula": "AS_TIMESTAMP(:reading date,'M/d/yy')",
                            "evaluated": {
                              "AS_TIMESTAMP(:reading date,'M/d/yy')": "1641254400000",
                              ":reading date": "1/4/22"
                            },
                            "result": "1641254400000"
                          },
                          {
                            "index": 1,
                            "name": "month",
                            "formula": "AS_TIMESTAMP(:reading date,'M/d/yy', roundDownTo='month')",
                            "evaluated": {
                              "AS_TIMESTAMP(:reading date,'M/d/yy', roundDownTo='month')": "1640995200000",
                              ":reading date": "1/4/22"
                            },
                            "result": "1640995200000"
                          },
                          {
                            "index": 2,
                            "name": "a",
                            "formula": ":a",
                            "evaluated": {
                              ":a": "A"
                            },
                            "result": "A"
                          },
                          {
                            "index": 3,
                            "name": "b*c",
                            "formula": ":b*:c",
                            "evaluated": {
                              ":b": "10",
                              ":c": "1"
                            },
                            "result": "10"
                          }
                        ]
                      },
                      {
                        "activityId": 1144,
                        "date": "2022-01-03T16:00:00.000Z",
                        "pipelineId": "01gwh2f5zwqryq789v42g1akrz",
                        "executionId": "01gwh2fb3g2e33ghb08pab5hma",
                        "auditId": "ab633d60-c50c-424e-add1-e6810766b1b4",
                        "createdAt": "2023-03-27T00:20:52.722Z",
                        "executionNo": 0,
                        "outputs": [
                          {
                            "index": 0,
                            "name": "time",
                            "formula": "AS_TIMESTAMP(:reading date,'M/d/yy')",
                            "evaluated": {
                              "AS_TIMESTAMP(:reading date,'M/d/yy')": "1641254400000",
                              ":reading date": "1/4/22"
                            },
                            "result": "1641254400000"
                          },
                          {
                            "index": 1,
                            "name": "month",
                            "formula": "AS_TIMESTAMP(:reading date,'M/d/yy', roundDownTo='month')",
                            "evaluated": {
                              "AS_TIMESTAMP(:reading date,'M/d/yy', roundDownTo='month')": "1640995200000",
                              ":reading date": "1/4/22"
                            },
                            "result": "1640995200000"
                          },
                          {
                            "index": 2,
                            "name": "a",
                            "formula": ":a",
                            "evaluated": {
                              ":a": "A"
                            },
                            "result": "A"
                          },
                          {
                            "index": 3,
                            "name": "b*c",
                            "formula": ":b*:c",
                            "evaluated": {
                              ":b": "10",
                              ":c": "1"
                            },
                            "result": "10"
                          }
                        ]
                      }
                    ]
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found.",
            "content": {
              "application/json": {
                "schema": {
                  "description": "Not found.",
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "message"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/activities": {
      "get": {
        "operationId": "listActivities",
        "summary": "List activities processed by a pipeline.",
        "tags": [
          "Activities"
        ],
        "description": "List activities processed by a pipeline.'\n\nPermissions:\n- `readers` of the group in context may list activities.\n",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "pipelineId",
            "required": false,
            "description": "Filters processed activities based on a specific pipeline."
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "executionId",
            "required": false,
            "description": "Filters processed activities based on a specific pipeline execution."
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "metric",
            "required": false,
            "description": "Filters processed activities that contributed to a specific metric."
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "dateFrom",
            "required": false,
            "description": "Filters processed activities that have a ISO8601 timestamp to be greater than or equal to this date. i.e. 2023-01-26T17:38:05.205Z"
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "dateTo",
            "required": false,
            "description": "Filters processed activities that have a ISO8601 timestamp to be lesser than or equal to this date.  i.e. 2023-01-26T17:38:05.205Z"
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "date",
            "required": false,
            "description": "Filters processed activities that have a ISO8601 timestamp to be exact match with a date.  i.e. 2023-01-26T17:38:05.205Z"
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "attributes",
            "required": false,
            "description": "Filters processed activities based on attributes in the format of `key1:value1[,key2:value2]`."
          },
          {
            "schema": {
              "type": "integer"
            },
            "in": "query",
            "name": "count",
            "required": false,
            "description": "Count of results to return."
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "fromToken",
            "required": false,
            "description": "Token used to paginate from (exclusive)."
          },
          {
            "schema": {
              "type": "boolean"
            },
            "in": "query",
            "name": "showHistory",
            "required": false,
            "description": "Retrieves full history of an activity"
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "uniqueKeyAttributes",
            "required": false,
            "description": "This parameter is required for viewing historical activities. The uniquely specified outputs of the pipeline should be provided for showHistory=true parameter `key1:value1[,key2:value2]`."
          },
          {
            "schema": {
              "type": "boolean"
            },
            "in": "query",
            "name": "showAggregate",
            "required": false,
            "description": "Show the aggregated value of activities."
          },
          {
            "in": "header",
            "name": "accept-version",
            "required": true,
            "description": "API version",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "header",
            "name": "accept",
            "required": true,
            "description": "Accepted Content Type",
            "schema": {
              "type": "string"
            }
          }
        ],
        "x-security-scopes": [
          "reader",
          "contributor",
          "admin",
          "superAdmin"
        ],
        "responses": {
          "200": {
            "description": "Success.",
            "content": {
              "application/json": {
                "schema": {
                  "description": "Success.",
                  "type": "object",
                  "properties": {
                    "activities": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/activityResource"
                      }
                    },
                    "pagination": {
                      "type": "object",
                      "properties": {
                        "lastEvaluatedToken": {
                          "description": "Token used to paginate to the next page of search result.",
                          "type": "number"
                        }
                      }
                    }
                  },
                  "required": [
                    "activities"
                  ]
                },
                "examples": {
                  "List of activities": {
                    "summary": "Paginated list of activities.",
                    "value": {
                      "activities": [
                        {
                          "date": "2022-01-02",
                          "fuel": "Lignite Coal",
                          "equipmentId": "furnace9",
                          "equipmentType": "furnace",
                          "co2": 101,
                          "pipelineId": "01gmf43ak9r1ghhvfaqb2wbcxp",
                          "executionId": "01gnb3v9nty57at170b7sfvdp0"
                        },
                        {
                          "date": "2022-01-04",
                          "fuel": "Aviation Gasoline",
                          "equipmentId": "thermaloxidizer5",
                          "equipmentType": "thermal oxidizer",
                          "co2": 335,
                          "pipelineId": "01gmf43ak9r1ghhvfaqb2wbcxp",
                          "executionId": "01gnb3v9nty57at170b7sfvdp0"
                        },
                        {
                          "date": "2022-01-03",
                          "fuel": "Fuel Gas",
                          "equipmentId": "oven8",
                          "equipmentType": "Oven",
                          "co2": 308,
                          "pipelineId": "01gmf43ak9r1ghhvfaqb2wbcxp",
                          "executionId": "01gnb3v9nty57at170b7sfvdp0"
                        }
                      ],
                      "pagination": {
                        "lastEvaluatedToken": 20
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/metrics": {
      "get": {
        "operationId": "listMetrics",
        "summary": "List metrics processed by a pipeline.",
        "tags": [
          "Metrics"
        ],
        "description": "List metrics processed by a pipeline.'\n\nPermissions:\n- `readers` of the group in context may list metrics.\n",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "name",
            "required": true,
            "description": "Filters metrics based on a specific metric name."
          },
          {
            "schema": {
              "type": "string",
              "enum": [
                "day",
                "week",
                "month",
                "quarter",
                "year"
              ]
            },
            "in": "query",
            "name": "timeUnit",
            "required": true,
            "description": "Time unit to aggregate metric by."
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "dateFrom",
            "required": false,
            "description": "Filters metrics that have a timestamp greater than or equal to this date."
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "dateTo",
            "required": false,
            "description": "Filters metrics that have a timestamp lesser than or equal to this date."
          },
          {
            "schema": {
              "default": false,
              "type": "boolean"
            },
            "in": "query",
            "name": "members",
            "required": true,
            "description": "If true, metrics are returned for the current groups members. If false (default) metrics are returned for the current group only."
          },
          {
            "schema": {
              "type": "number"
            },
            "in": "query",
            "name": "version",
            "required": false,
            "description": "Filters metrics based on a specific version."
          },
          {
            "schema": {
              "type": "integer"
            },
            "in": "query",
            "name": "count",
            "required": false,
            "description": "Count of results to return."
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "fromToken",
            "required": false,
            "description": "Token used to paginate from (exclusive)."
          },
          {
            "in": "header",
            "name": "accept-version",
            "required": true,
            "description": "API version",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "header",
            "name": "accept",
            "required": true,
            "description": "Accepted Content Type",
            "schema": {
              "type": "string"
            }
          }
        ],
        "x-security-scopes": [
          "reader",
          "contributor",
          "admin",
          "superAdmin"
        ],
        "responses": {
          "200": {
            "description": "Success.",
            "content": {
              "application/json": {
                "schema": {
                  "description": "Success.",
                  "type": "object",
                  "properties": {
                    "metrics": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/metricResource"
                      }
                    }
                  },
                  "required": [
                    "metrics"
                  ]
                },
                "examples": {
                  "List of metrics": {
                    "summary": "Paginated list of metrics.",
                    "value": {
                      "metrics": [
                        {
                          "date": "2021-12-31T16:00:00.000Z",
                          "metricId": "01GZ3M39CZXVQGHV46H8A9Z9SV",
                          "name": "ghg:scope1",
                          "timeUnit": "month",
                          "month": 1,
                          "year": 2022,
                          "hierarchyValue": 146,
                          "groupValue": 34,
                          "subGroupsValue": 112,
                          "version": "latest"
                        },
                        {
                          "date": "2022-01-31T16:00:00.000Z",
                          "metricId": "01GZ3M39CZXVQGHV46H8A9Z9SV",
                          "name": "ghg:scope1",
                          "timeUnit": "month",
                          "month": 2,
                          "year": 2022,
                          "hierarchyValue": 54,
                          "groupValue": 22,
                          "subGroupsValue": 32,
                          "version": "latest"
                        },
                        {
                          "date": "2022-02-28T16:00:00.000Z",
                          "metricId": "01GZ3M39CZXVQGHV46H8A9Z9SV",
                          "name": "ghg:scope1",
                          "timeUnit": "month",
                          "month": 3,
                          "year": 2022,
                          "hierarchyValue": 360,
                          "groupValue": 21,
                          "subGroupsValue": 339,
                          "version": "latest"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://localhost"
    }
  ],
  "security": [],
  "tags": [
    {
      "name": "Pipeline Executions",
      "description": "Pipeline Executions"
    }
  ]
}